server:
  port: 8888
  #  tomcat:
  #    basedir: C:/Users/18399/Desktop/
  ssl:
    enabled: false
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    #应用的名称，可选
    name: reggie
  #  datasource:
  #    druid:
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  #      username: root
  #      password: 123456
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.99.194.162:3306/xyl?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://112.124.201.110:3306/xyl?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 47.99.194.162
    port: 6379
    database: 2
    password: 1807090626@Hgm
  cache:
    redis:
      #设置缓存有效时间
      time-to-live: 1800000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /usr/local/javaapp/xyl_img/
#  path: C:/Users/18399/Desktop/图片资源/

knife4j:
  enable: true

#七牛配置
qiniu:
  accessKey: ID_Vi-bQ_x43W3KSxy8y9WuaAp2H38tYEM3tslEF
  secretKey: 6qU71m1te4NKQI1ue5bmCL97x9eeaX5Zrih9AtCl
  bucket: serms
  domain: https://serms.xyz/

# easy-captcha配置
easycaptcha:
  #  验证码类型配置 查看 LoginProperties 类
  code-type: arithmetic